#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')

	if [ "systemd" == "$INITSYS" ]; then
		if [ -e /etc/systemd/system/cymtv-remote.service ]; then
			rm /etc/systemd/system/cymtv-remote.service
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
		if [[ "$parsedVersion" -gt "360" ]]; then
			sudo -H pip3 install pynput
		fi
		cp /usr/share/cymtv-remote/files/systemd/cymtv-remote.service /etc/systemd/system/cymtv-remote.service
		systemctl daemon-reload
		systemctl enable cymtv-remote
		systemctl start cymtv-remote
	fi
fi
