#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		if [ "systemd" == "${INITSYS}" ]; then
			systemctl stop cymtv-remote || true
			systemctl disable cymtv-remote || true
			rm /etc/systemd/system/cymtv-remote.service || true
		fi
        ;;
esac

exit 0
